#!/bin/bash
# CLI tool for HApiMonitor

function check_updates() {
  CURRENT_VERSION=$(hapimonitor.py --version)
  LATEST_VERSION=$(curl -s https://api.github.com/repos/yourdawi/hapimonitor/releases/latest | grep tag_name | cut -d '"' -f 4)
  
  if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
    echo "New version available: $LATEST_VERSION"
    echo "Updating..."
    curl -sSL https://raw.githubusercontent.com/yourdawi/hapimonitor/main/install.sh | sudo bash
  else
    echo "Already up to date"
  fi
}

case "$1" in
  "-up")
    check_updates
    ;;
  *)
    echo "Usage: hapimonitor-cli [-up]"
    ;;
esac